import { assessment } from './scoring.js';
import { META, QS, STEPS, POLICY_CATEGORIES } from './content.js';
export const names=Object.keys(META);
export const labels={good:'Low Risk',warn:'Medium Risk',risk:'High Risk'};
export const riskIcons={good:'🟢',warn:'🟡',risk:'🔴'};
export const riskMeaning={good:'Continue with the documented manager process and confirm company policy.',warn:'Pause before formal action and consult HR about the identified gaps or uncertainty.',risk:'Stop. HR and, when appropriate, legal review are required before action.'};
export const riskSummary=s=>`${riskIcons[s.level]} ${labels[s.level].toUpperCase()}\nRisk scale: 🟢 Low  ·  🟡 Medium  ·  🔴 High\n${riskMeaning[s.level]}`;
export const reviewAnswer=(q,answer,note,index)=>[header(`Question ${index+1}`),section(q.q+(answerHelp(q)?'\n'+answerHelp(q):'')),section(`🔷 ANSWER: ${(answer||'Unanswered').toUpperCase()}\n📝 NOTE: ${note||'No note provided'}`)];
export const plain=text=>({type:'plain_text',text:String(text)});
export const section=text=>({type:'section',text:plain(text||'—')});
export const mrkdwnSection=text=>({type:'section',text:{type:'mrkdwn',text:String(text||'—')}});
export const header=text=>({type:'header',text:plain(text)});
export const divider=()=>({type:'divider'});
export const context=text=>({type:'context',elements:[plain(text)]});
export const mrkdwnContext=text=>({type:'context',elements:[{type:'mrkdwn',text:String(text||'—')}]});
export const button=(text,action_id,value='')=>({type:'button',text:plain(text),action_id,value:value||action_id});
export const actions=(...elements)=>({type:'actions',elements:elements.map((e,i)=>({...e,action_id:e.action_id+(elements.some((x,j)=>j<i&&x.action_id===e.action_id)?'_nav'+i:'')}))});
export const option=(text,value)=>({text:plain(text),value});
export const input=(id,label,element,optional=false)=>({type:'input',block_id:id,label:plain(label),element:{...element,action_id:'value'},optional});
export const textInput=(id,label,value='',max=1500)=>input(id,label,{type:'plain_text_input',multiline:true,max_length:max,...(value?{initial_value:value}:{})},true);
export const fileInput=(id,label,max=5)=>input(id,label,{type:'file_input',max_files:max,filetypes:['pdf','doc','docx','xls','xlsx','csv','txt','png','jpg','jpeg']},true);
export const select=(id,label,options,value,optional=false)=>input(id,label,{type:'static_select',options,...(value?{initial_option:options.find(o=>o.value===value)}:{})},optional);
export const modal=(callback,blocks,meta={},submit)=>({type:'modal',callback_id:callback,title:plain('People Action Check'),close:plain('Close'),private_metadata:JSON.stringify(meta),blocks,...(submit?{submit:plain(submit)}:{})});
export const questions=r=>r.scenarios.flatMap(n=>QS[n]);
export const answerHelp=q=>q.q==='Is this a first offense, or is there prior disciplinary history?'?'Answer key: Yes = offense history established; No = not established; Don’t know = uncertain.':'';
export const score=assessment;
export const member=id=>`<@${id}>`;
export const slackDate=value=>{const ms=Date.parse(value||'');return Number.isFinite(ms)?`<!date^${Math.floor(ms/1000)}^{date_short_pretty} at {time}|${String(value).slice(0,16)}>`:'Date unavailable';};
export const footer=()=>section('General guidance only — not legal advice. © 2026 Melissa A. Weiss. All rights reserved.');
export function picker(){return modal('pick',[header('Start a people action check'),section('Select the situations you want to assess. Your work stays private until you explicitly submit a snapshot to HR.'),context('Restricted HR data · Use the minimum employee information needed'),divider(),input('scenarios','Situation type',{type:'multi_static_select',options:names.map(n=>option(n,n))}),textInput('employee','Employee name or case reference (optional)','',150)],{},'Continue');}
export function wizard(r,policies=[]){
 const p=r.page||0, n=r.scenarios[p], m=META[n], meta={id:r.id,revision:r.revision};
 if(r.stage==='context')return modal('context',[header(`${m.icon} ${n}`),context(`Situation ${p+1} of ${r.scenarios.length} · ${m.riskLabel}`),section(m.description),divider(),header('🟦 Common examples'),section(m.examples.map(x=>'• '+x).join('\n')),divider(),header('🟨 Documentation checklist'),section('Gather and preserve these records as you work through the check.'),section(m.docTips.map((x,i)=>`${i+1}. ${x}`).join('\n')),context('You can attach files and links securely from the completed assessment before submitting it to HR.'),divider(),section('Watch for: '+m.watch),section('Contact HR: '+m.contactHR)],meta,p<r.scenarios.length-1?'Next situation':'Start the check');
 const offset=p*5; const blocks=[header(n),context(`Assessment ${p+1} of ${r.scenarios.length} · ${r.answers.filter(Boolean).length} of ${questions(r).length} answered`),section('Complete each answer to calculate the assessment. Save and close keeps submitted answers and notes.'),section('📎 Documentation matters: use the notes under each answer to record dates, facts, conversations, and supporting records.'),divider()];
 for(const [i,q] of QS[n].entries()){const k=offset+i,suffix='_'+r.revision; blocks.push(section(`${k+1}. ${q.q}${q.critical?' [Critical]':''}\nWhy this matters: ${q.hint}${answerHelp(q)?'\n'+answerHelp(q):''}`),select('q'+k+suffix,'Answer', [option('Yes','yes'),option('No','no'),option("Don’t know",'unknown')],r.answers[k],true),textInput('n'+k+suffix,'Notes (optional)',r.notes[k]));}
 const rel=policies.filter(d=>POLICY_CATEGORIES.find(c=>c.id===d.category)?.scenarios.includes(n));
 if(rel.length)blocks.push(section('Relevant policies: '+rel.slice(0,8).map(d=>d.name).join(', ')+(rel.length>8?` and ${rel.length-8} more`:'')),actions(button('Company policies','policies')));
 blocks.push(select('nav_'+p+'_'+r.revision,'After submitting this page',[option(p===r.scenarios.length-1?'View assessment':'Next situation','next'),option('Save and close','save'),...(p?[option('Previous situation','back')]:[])],'next'),actions(button('Clear page','clear_answers',r.id)));
 return modal('answers',blocks,meta,'Submit answers');
}
export function report(r){const s=score(r),files=[...(r.evidenceFiles||[]),...(r.hrEvidenceFiles||[])];return ['People Action Check',`Employee: ${r.employee||'Not specified'}`,`Situations: ${r.scenarios.join(', ')}`,`Result: ${labels[s.level]}`,`Date: ${r.completedAt||''}`,'',...questions(r).flatMap((q,i)=>[`${i+1}. ${q.q}${q.critical?' [Critical]':''}${answerHelp(q)?'\n'+answerHelp(q):''}`,`Answer: ${r.answers[i]||'Unanswered'}`,`Note: ${r.notes[i]||''}`]),'',...r.scenarios.flatMap(n=>[n,...STEPS[n][s.level],META[n].contactHR]),'Supporting links / context: '+(r.attachments||'None'),'Attached documents: '+(files.length?files.map(f=>f.name||f.title||f.id).join(', '):'None'),scoringNotice(r),'General guidance only — not legal advice.','© 2026 Melissa A. Weiss. All rights reserved.'].join('\n');}
export function evidenceSummary(r){const manager=r.evidenceFiles||[],hr=r.hrEvidenceFiles||[];const lines=[];if(manager.length)lines.push('Manager documents: '+manager.map(f=>f.name||f.title||f.id).join(', '));if(hr.length)lines.push('HR documents: '+hr.map(f=>f.name||f.title||f.id).join(', '));return lines.join('\n')||'No documents attached.';}
export function result(r,page=0,hr=false){page=pageIndex(page,r.scenarios.length,1);const s=score(r),n=r.scenarios[page];return modal('result',[header('Risk assessment'),section(`${riskSummary(s)}\n\nEmployee or case: ${r.employee||'Unnamed employee'}`),context(`Situation ${page+1} of ${r.scenarios.length} · ${r.reviewStatus||'Private draft'} · Yes ${s.yes} · No ${s.no} · Don’t know ${s.unk}`),divider(),section(s.crit?'A critical response or uncertainty triggered the High Risk result.':'The result reflects the weighted answers across this check.'),section(scoringNotice(r)),divider(),header('📎 Documentation & supporting evidence'),section('Keep the factual record together before taking action or submitting to HR.'),...textSections(r.attachments||'No supporting links or context added yet.'),section(evidenceSummary(r)),...(!hr?[actions({...button('Add documentation','attachments',r.id),style:'primary'})]:[]),divider(),header(n),section(STEPS[n][s.level].map((x,i)=>`${i+1}. ${x}`).join('\n')),section(META[n].contactHR),divider(),header('Recorded answers'),...QS[n].flatMap((q,i)=>reviewAnswer(q,r.answers[page*5+i],r.notes[page*5+i],page*5+i)),actions(...r.scenarios.map((_,i)=>({...button('Situation '+(i+1),'result_page_'+i,JSON.stringify({id:r.id,page:i,hr})),accessibility_label:'View '+r.scenarios[i]}))),...(hr?[mrkdwnSection(`Submitted by ${member(r.submittedBy)} · ${slackDate(r.submittedAt)}`),select('status','Review status',['New','In review','Closed'].map(x=>option(x,x)),r.reviewStatus||'New'),textInput('reviewNote','HR review note',r.reviewNote),fileInput('hrFiles','Attach HR documents (optional)',5)]:[divider(),actions(button('Edit answers','edit',r.id),button('Report to my DM','export',r.id),button('Send to me and HR','share',r.id),button('Follow-up','followup',r.id)),actions(button('Run again','rerun',r.id),button('Delete check','delete_check',r.id)),actions(button('Submission delivery','submission_status',r.id))]),footer()],{id:r.id,revision:r.reviewRevision||0},hr?'Save review':undefined);}
export function home(checks,policies,hr=false){const recent=checks.slice(0,3);return {type:'home',blocks:[header('People Action Check'),section('Private decision support for consistent, documented people-management actions.'),context(hr?'HR reviewer access · Governance controls enabled':'Manager workspace · Policies are read-only · Your checks stay private until submitted'),actions(button('Start a new check','new'),button('My history','my_history'),button('Refresh','refresh_home')),...(checks.length?[actions(button('Clear my history','clear_history'))]:[]),actions(button('Company policies','policies'),...(hr?[button('HR review queue','inbox'),button('Governance Center','governance'),button('Add policy','add_policy')]:[])),divider(),header(checks.length?'Recent activity':'Get started'),...(checks.length?recent.flatMap(r=>historyCard(r)):[section('No saved checks yet. Start a new check to document a situation and assess next steps.')]),...(checks.length>3?[actions(button(`View all ${checks.length} checks`,'my_history'))]:[]),footer()]};}
export function history(checks,page=0){page=pageIndex(page,checks.length,10);const completed=checks.filter(r=>r.stage==='done').length,inProgress=checks.length-completed,chunk=checks.slice(page*10,page*10+10);return modal('history',[header('My history'),section(`${checks.length} total checks\n${completed} completed · ${inProgress} in progress`),context('Private manager history · Only you can access these personal records'),divider(),...(chunk.length?chunk.flatMap(r=>historyCard(r)):[section('No saved checks yet. Start a new check from the Home tab.')]),...(checks.length?[actions(...(page?[button('Previous','history_page',String(page-1))]:[]),...(checks.length>(page+1)*10?[button('Next','history_page',String(page+1))]:[]),button('Refresh','history_page',String(page)))]:[])],{page});}
export function historyCard(r){const done=r.stage==='done',s=done?score(r):null,status=done?labels[s.level]:'In progress',icon=done?riskIcons[s.level]:'◐',date=(done?r.completedAt:r.updatedAt)||r.createdAt||'';return [section(`${icon} ${r.employee||'Unnamed employee'}\n${status} · ${r.scenarios.join(', ')}\n${date?'Updated '+date.slice(0,10):'Date unavailable'}${r.followup?' · Follow-up '+r.followup:''}`),actions(button(done?'View assessment':'Resume check','open',r.id))];}
export function policyList(docs,hr,page=0){page=pageIndex(page,docs.length,10);return modal('policy_list',[section('Company Policies — shared across your workspace'+(docs.length?'':'\nNo policies have been added yet.')),...docs.slice(page*10,page*10+10).flatMap(d=>[section(d.name+' · '+POLICY_CATEGORIES.find(c=>c.id===d.category)?.label),actions(button('Read','read_policy',d.id),...(hr?[button('Edit','edit_policy',d.id),button('Delete','delete_policy',d.id)]:[]))]),actions(...(page?[button('Previous','policy_page',String(page-1))]:[]),...(docs.length>(page+1)*10?[button('Next','policy_page',String(page+1))]:[]),button('Refresh','policy_page',String(page)))]);}
export function policyForm(d={}){return modal('policy_save',[{...textInput('name','Document name',d.name,150),optional:false},select('category','Category',POLICY_CATEGORIES.map(c=>option(c.label,c.id)),d.category||'handbook'),{...textInput('content','Policy text or document URL',d.content,3000),optional:false}],{id:d.id,revision:d.revision||0},'Save');}

export function pageIndex(page,count,size){
 const n=Number(page);return Number.isSafeInteger(n)&&n>=0?Math.min(n,Math.max(0,Math.ceil(count/size)-1)):0;
}
export function textSections(text){const chars=Array.from(text);const blocks=[];for(let i=0;i<chars.length;i+=2800)blocks.push(section(chars.slice(i,i+2800).join('')));return blocks;}
export function scoringNotice(r){return r.scoringVersion===2?'Assessment uses polarity-aware scoring (v2). Guidance is not clearance to act.':'Legacy assessment: source scoring has known answer-polarity errors. Edit and complete the check to recalculate with v2. Do not rely on this result for clearance.';}
export function notice(text){return modal('notice',[...textSections(text)]);}
export function supportingForm(r,{clear=false}={}){return modal('attachments_save',[header('📎 Add documentation'),section('Add factual notes, secure document links, and relevant files. Examples include coaching notes, emails, signed acknowledgements, timelines, policies, and work samples.'),context('Use the minimum employee information needed · Slack workspace access and retention rules apply'),textInput('links','Documentation notes and secure links',clear?'':r.attachments,3000),fileInput('files','Attach supporting documents (optional)',5),section(clear?'The visible form is clear. Submit to replace saved notes/links; existing uploaded document references remain listed until the record is updated.':evidenceSummary(r)),actions(button('Clear form','clear_evidence_form',r.id))],{id:r.id,revision:r.revision},'Save documentation');}
export function followupForm(r){return modal('followup_save',[textInput('date','Follow-up date (YYYY-MM-DD); blank to dismiss',r.followup,10),section('Due dates appear in your App Home. No automatic reminder messages are sent.')],{id:r.id,revision:r.revision},'Save');}
export function shareForm(r,hrs){return modal('share_confirm',[header('Submit for HR review'),section('This sends HR a private Slack notification and adds an immutable snapshot to the HR inbox.'),section('Included: employee name, situations, answers, notes, supporting links, and attached-document references.'),mrkdwnSection('HR reviewers: '+hrs.map(member).join(', ')),context('A Word report is sent to your private app DM. Shared snapshots remain in the HR inbox if you later edit or delete your personal check.')],{id:r.id,revision:r.revision},'Submit to HR');}
export function deleteForm(id,type){return modal('delete_confirm',[section('Delete this '+type+'? This cannot be undone. HR snapshots and files already delivered to Slack remain available.')],{id,type},'Delete');}
export function clearHistoryForm(count){return modal('clear_history_confirm',[header('Clear my history'),section(`Delete all ${count} personal check${count===1?'':'s'} from your App Home?`),section('This cannot be undone. HR snapshots, Slack messages, and files already submitted or delivered remain available under their separate retention rules.')],{count},'Clear history');}
export function policyRead(d){return modal('policy_read',[section(d.name),...textSections(d.content),actions(button('Back to policies','policy_page','0'))]);}
export function inbox(rows,page=0){page=pageIndex(page,rows.length,15);return modal('inbox',[header('HR review queue'),context(`${rows.length} total submission${rows.length===1?'':'s'} · Private to configured HR reviewers`),...(rows.length?rows.slice(page*15,page*15+15).flatMap(r=>{const s=score(r);return [mrkdwnSection(`${riskIcons[s.level]} *${r.employee||'Unnamed employee'}*\n${labels[s.level]} · ${r.reviewStatus} · ${r.scenarios.join(', ')}\nSubmitted ${slackDate(r.submittedAt)} by ${member(r.submittedBy)}`),actions(button('Open review','review',r.id))];}):[section('No HR submissions are waiting for review.')]),actions(...(page?[button('Previous','inbox_page',String(page-1))]:[]),...(rows.length>(page+1)*15?[button('Next','inbox_page',String(page+1))]:[]),button('Refresh','inbox_page',String(page)))]);}
export function hrMessage(record){const r=typeof record==='string'?{id:record,employee:'Unnamed employee',scenarios:[],reviewStatus:'New'}:record,s=r.answers?score(r):null;return {text:`People Action Check ready for HR review: ${r.employee||'Unnamed employee'}.`,blocks:[header('New HR review'),section(`${s?riskIcons[s.level]+' ':''}${r.employee||'Unnamed employee'}\n${s?labels[s.level]+' · ':''}${r.scenarios?.join(', ')||'People-management assessment'}`),mrkdwnContext(`Status: ${r.reviewStatus||'New'} · Submitted ${r.submittedAt?slackDate(r.submittedAt):'just now'}`),actions(button('Open review','review',r.id))]};}
export function managerReviewMessage(r){const s=score(r);return {text:`HR updated your People Action Check: ${r.reviewStatus}.`,blocks:[header('HR review update'),section(`${riskIcons[s.level]} ${r.employee||'Unnamed employee'}\n${labels[s.level]} · ${r.scenarios.join(', ')}`),section(`Review status: ${r.reviewStatus}\nHR note: ${r.reviewNote||'No note provided'}`),mrkdwnContext(`Reviewed ${r.reviewedAt?slackDate(r.reviewedAt):'just now'} · Private manager notification`)]};}
export function deliveryView(s){const items=Object.values(s.delivery||{}),failed=items.some(x=>x.status==='failed'),pending=items.some(x=>['pending','sending'].includes(x.status)),assessment=Array.isArray(s.scenarios)&&Array.isArray(s.answers)?score(s):null;const lines=items.map(x=>`${x.report?'Manager report':'HR notification'}: ${x.status==='sent'?'Delivered':x.status==='failed'?'Needs retry':'Sending'}${x.error?' — '+String(x.error).slice(0,500):''}`);return modal('delivery',[header(failed?'Submission saved — delivery needs attention':pending?'Submitting to HR':'Submitted successfully'),...(assessment?[section(riskSummary(assessment)),divider()]:[]),section('HR review queue: Saved'),...textSections(lines.length?lines.join('\n'):'Delivery status is not available.'),...(failed?[section('A Slack delivery failed. Retry sends only items that were not completed.'),actions(button('Refresh status','delivery_status',s.id),button('Retry failed delivery','retry_delivery',s.id))]:pending?[section('Slack is still processing the delivery.'),actions(button('Refresh status','delivery_status',s.id))]:[section('HR can now open this case from the private HR review queue.'),actions(button('Refresh status','delivery_status',s.id))])]);}
export function governanceCenter({audits=[],checks=0,submissions=0,policies=0,reviewers=0,retentionDays=0}){return modal('governance',[header('Governance Center'),section('Data classification: Restricted HR\nSystem of record: encrypted persistent application storage\nSlack delivery: workspace retention and administrator controls apply'),context(`${reviewers} authorized HR reviewer${reviewers===1?'':'s'} · ${retentionDays?retentionDays+'-day retention':'Automatic retention disabled'}`),divider(),header('Control status'),section(`Access control: HR allowlist enforced server-side\nReview workflow: New → In review → Closed\nPersonal checks: ${checks}\nHR submissions: ${submissions}\nCompany policies: ${policies}`),divider(),header('Recent audit activity'),...(audits.length?audits.slice(0,20).map(e=>mrkdwnSection(`${slackDate(e.createdAt)} · ${e.action}\nActor: ${member(e.actor)} · ${e.targetKind}`)):[section('No governed events recorded yet.')]),actions(button('Refresh controls','governance'))]);}
