import test from 'node:test';
import assert from 'node:assert/strict';
import {META,QS,STEPS,POLICY_CATEGORIES,computeScore} from '../src/content.js';
import * as v from '../src/views.js';
import {Store} from '../src/store.js';
export function validate(view){assert.ok(view.blocks.length<=100);assert.ok(view.blocks.length);if(view.type==='modal'){assert.ok(view.title.text.length<=24);if(view.blocks.some(b=>b.type==='input'))assert.ok(view.submit);}const ids=new Set();for(const b of view.blocks){if(b.block_id){assert.ok(!ids.has(b.block_id));ids.add(b.block_id);}if(b.type==='section')assert.ok(b.text.text.length<=3000);if(b.type==='input'){assert.ok(b.label.text.length<=200);const e=b.element;if(e.options){assert.ok(e.options.length<=100);for(const o of e.options)assert.ok(o.text.text.length<=75);} }if(b.type==='actions'){assert.ok(b.elements.length<=25);const a=new Set();for(const e of b.elements){assert.ok(!a.has(e.action_id));a.add(e.action_id);assert.ok(e.text.text.length<=75);}}}}
export const sample=(scenarios=v.names)=>({id:'example',revision:1,employee:'Example employee',stage:'done',page:0,scenarios,answers:scenarios.flatMap(()=>Array(5).fill('yes')),notes:scenarios.flatMap(()=>Array(5).fill('')),completedAt:'2026-09-29T12:00:00Z'});
test('complete content: 10 scenarios and 50 questions',()=>{assert.equal(v.names.length,10);assert.equal(Object.values(QS).flat().length,50);for(const n of v.names){assert.ok(META[n].examples.length);for(const l of ['good','warn','risk'])assert.equal(STEPS[n][l].length,3);}});
test('critical no and unknown override; exact thresholds',()=>{for(const a of ['no','unknown'])assert.equal(computeScore([{weight:2,critical:true}],[a]).level,'risk');const qs=Array(20).fill({weight:1,critical:false});for(const [n,expected] of [[3,'good'],[4,'warn'],[9,'warn'],[10,'risk']])assert.equal(computeScore(qs,qs.map((_,i)=>i<n?'no':'yes')).level,expected);});
test('every scenario, all combined pages, long notes satisfy surface limits',()=>{validate(v.picker());validate(v.home(Array(35).fill(sample()),[],true));validate(v.policyForm());validate(v.policyList([],true));for(const selection of [...v.names.map(n=>[n]),v.names]){const r=sample(selection);r.notes=r.notes.map(()=>'N'.repeat(1500));for(let p=0;p<selection.length;p++){r.page=p;r.stage='context';validate(v.wizard(r));r.stage='questions';validate(v.wizard(r));validate(v.result(r,p));validate(v.result(r,p,true));}}});
test('ownership isolation, updates, deletes and persistence',()=>{const s=new Store(':memory:');const r=s.save('check','T:U1',{answers:['yes']});assert.throws(()=>s.get(r.id,'T:U2'));assert.throws(()=>s.delete(r.id,'T:U2'));assert.equal(s.list('check','T:U2').length,0);s.save('check','T:U1',{...r,answers:['no']});assert.equal(s.get(r.id,'T:U1').answers[0],'no');s.delete(r.id,'T:U1');assert.throws(()=>s.get(r.id));s.close();});
test('report includes every question, note, and next step',()=>{const r=sample();r.notes[0]='Unique note';const text=v.report(r);assert.ok(text.includes('Unique note'));for(const q of Object.values(QS).flat())assert.ok(text.includes(q.q));});
