const pptxgen = require('pptxgenjs');
const path = require('path');
const C = { ink:'242038', muted:'5E6070', purple:'634AA2', teal:'087D73', lavender:'EEEAF8', mint:'E5F4EF', gray:'F1F3F6', amber:'FFF0D5', red:'AF3648', green:'17734A' };
const root = __dirname;
function deck(title) { const p=new pptxgen(); p.layout='LAYOUT_WIDE'; p.author='Melissa A. Weiss'; p.title=title; p.subject='People Action Check — review version, October 9, 2026'; p.lang='en-US'; p.theme={headFontFace:'Arial',bodyFontFace:'Arial',lang:'en-US'}; return p; }
function text(s,t,x,y,w,h,size=18,bold=false,color=C.ink) { s.addText(t,{x,y,w,h,fontFace:bold?'Arial':'Arial',fontSize:size,bold,color,margin:0,breakLine:false,paraSpaceAfterPt:6,valign:'top'}); }
function box(p,s,x,y,w,h,fill) {s.addShape(p.ShapeType.roundRect,{x,y,w,h,rectRadius:.12,line:{color:fill,transparency:100},fill:{color:fill}});}
function title(p,head,sub,n) {const s=p.addSlide();s.background={color:'FFFFFF'};text(s,head,.6,.45,12.1,.65,34,true);text(s,sub,.62,1.16,12,.5,17,false,C.muted);text(s,'PEOPLE ACTION CHECK  |  REVIEW VERSION  |  OCTOBER 9, 2026',.62,7.02,11.7,.18,10,false,C.muted);text(s,String(n),12.15,7.0,.55,.2,11,false,C.muted);return s;}
function card(p,s,x,y,w,h,head,body,fill=C.gray,size=21){box(p,s,x,y,w,h,fill);text(s,head,x+.26,y+.25,w-.52,.5,24,true);text(s,body,x+.26,y+.95,w-.52,h-1.15,size);}
function bullets(s,items,x,y,w,h,size=21){s.addText(items.map((t,i)=>({text:t,options:{bullet:{indent:size},hanging:4,breakLine:i<items.length-1}})),{x,y,w,h,fontFace:'Arial',fontSize:size,color:C.ink,margin:0,paraSpaceAfterPt:14,valign:'top'});}
function note(s,t){s.addNotes(t);}
function overview(p){const s=p.addSlide();s.background={color:'FFFFFF'};
 text(s,'PEOPLE ACTION CHECK',.6,.4,8.2,.5,30,true);text(s,'Private Slack guidance for documented people-management actions',.62,1.0,11.8,.35,16,false,C.muted);
 box(p,s,9.58,.42,3.12,.48,C.mint);text(s,'CLOUD CONNECTION VERIFIED',9.75,.56,2.77,.18,10.6,true,C.teal);
 text(s,'HOW A CHECK MOVES',.62,1.6,11.9,.3,18,true);
 const steps=[['Choose','Select from 10 situations and read the relevant guidance.'],['Assess','Answer five questions per situation; add notes and evidence.'],['Review','See Low, Medium or High risk and suggested next steps.'],['Submit to HR','Share the case for HR review, documentation and reporting.']];
 steps.forEach(([h,b],i)=>{const x=.62+i*3.12;box(p,s,x,2.02,2.73,1.65,i%2?C.mint:C.lavender);s.addShape(p.ShapeType.ellipse,{x:x+.19,y:2.23,w:.4,h:.4,line:{transparency:100,color:C.purple},fill:{color:C.purple}});s.addText(String(i+1),{x:x+.19,y:2.31,w:.4,h:.2,fontFace:'Arial',fontSize:12,bold:true,color:'FFFFFF',align:'center',margin:0});text(s,h,x+.7,2.24,1.85,.35,17,true);text(s,b,x+.2,2.86,2.33,.62,13.5);});
 box(p,s,.62,3.96,6.05,2.38,C.lavender);text(s,'WHAT MANAGERS & HR CAN DO',.88,4.23,5.52,.35,18,true);text(s,'Managers save and resume private checks, add documentation, request Word reports and submit to HR.',.88,4.78,5.5,.57,15);text(s,'HR reviews full submitted cases, downloads reports, adds documents and uses the Governance Center.',.88,5.52,5.5,.57,15);
 box(p,s,6.91,3.96,5.81,2.38,C.mint);text(s,'HOW IT RUNS & WHO GOVERNS',7.17,4.23,5.29,.35,18,true);
 [['Slack',7.17,1.15],['Cloudflare',8.82,1.5],['Supabase',10.82,1.58]].forEach(([h,x,w])=>{box(p,s,x,4.78,w,.43,'FFFFFF');text(s,h,x,4.9,w,.18,12.5,true,C.teal);});text(s,'→',8.47,4.86,.25,.25,18,false,C.teal);text(s,'→',10.46,4.86,.25,.25,18,false,C.teal);
 text(s,'Cloudflare hosts the app; Supabase stores records. Slack stores messages and uploaded files.',7.17,5.43,5.22,.52,14.1);
 text(s,'PRIVATE BY DESIGN',.62,6.69,2.1,.2,11,true,C.purple);text(s,'Private drafts; HR reviews submitted case details. Access, retention and audit controls are built in.\nNo generative AI. Wider rollout still needs access, recovery and delivery checks.',2.86,6.55,9.83,.61,13.4);
 note(s,'Reviewed against src/handlers.js, src/views.js, src/scoring.js, src/worker.js and cloud SQL. Live October 9: Slack interactivity saved and verified after reload; history and saved assessment opened; policy empty state and HR queue opened; new-check selection modal opened without saving. Storage health returned HTTP 200 / ok after deployment. Feature claims are supported by implementation and automated tests; not every feature was exercised live in this repair. Cloud backup/restore has not been verified. No external AI provider is called by People Action Check. This is separate from Performance Check-In.');return s;}
async function main(){const one=deck('People Action Check — One-Page Overview');overview(one);await one.writeFile({fileName:path.join(root,'People Action Check — One-Page Overview.pptx')});
 const p=deck('People Action Check — Updated Pilot Overview');overview(p);
 let s=title(p,'A private workflow for managers','Assess the situation, keep the factual record, and choose when to share',2);
 card(p,s,.62,1.98,6.04,4.57,'Assess and document','Choose one or more situations. Read examples and documentation guidance.\n\nAnswer five questions per situation with Yes, No or Don’t know. Add notes, links and Slack files.',C.lavender,22);
 card(p,s,6.91,1.98,5.81,4.57,'Save, review and continue','Save a partial check and resume from My history. Review recorded answers and suggested next steps.\n\nRequest a Word report or set a follow-up date. Dates are visible; reminders are not automatically sent.',C.mint,22);
 note(s,'Implementation: picker/wizard/history/supportingForm/followupForm in src/views.js; registered callbacks in src/handlers.js. Report generation is DOCX delivered via Slack DM, not email. Follow-up dates do not schedule notifications. Tests cover partial saves, evidence, report export and follow-up, with external Slack calls substituted.');
 s=title(p,'HR reviews explicitly shared cases','Case details, supporting documents, HR review and downloadable reports',3);
 const flow=[['Confirm sharing','The manager sees the recipients and disclosure before submitting.'],['Review the case','HR sees answers, notes, risk guidance and supporting documents; download Word reports to their private app DM.'],['Record a response','HR adds documents, review notes and status; the manager receives a private update.']];
 flow.forEach(([h,b],i)=>card(p,s,.62+i*4.15,2.05,3.83,3.28,h,b,i%2?C.mint:C.lavender,19));
 box(p,s,.62,5.68,12.1,1.03,C.gray);text(s,'HR manages the policy library and Governance Center. Submitted answers are preserved while HR review details can be updated.',.89,5.88,11.55,.43,20);
 note(s,'HR Download Word report button added and deployed October 9, Worker f01a6484-2427-4ec9-a480-b96102ccda3f. Export is restricted server-side to authorized HR reviewers and reads the saved team submission. Includes saved HR status, note, reviewer and evidence references. Save review edits before exporting. Live Slack download delivery remains unverified; automated real DOCX and authorization tests pass. src/handlers.js preserves submitted answers and gates HR access; HR sees the full assessment, adds HR evidence and maintains review fields. Governance Center is implemented, not future work. HR review update notification is implemented and tested. Delivery failure/retry is tracked separately from saving the HR snapshot. Current live repair verified HR queue access only; it did not send notifications or alter existing reviews.');
 s=title(p,'Risk guidance supports human decisions','Responses produce a rule-based assessment, not an employment decision',4);
 const levels=[['LOW',C.green,C.mint,'Use the guidance','Review the suggested steps and keep documentation current.'],['MEDIUM','946000',C.amber,'Resolve the gaps','Review uncertainty and documentation; consult HR as appropriate.'],['HIGH',C.red,'F9E7EB','Stop for review','The app directs HR and, when appropriate, legal review before action.']];
 levels.forEach(([label,col,fill,h,b],i)=>{const x=.62+i*4.15;box(p,s,x,2.07,3.83,3.55,fill);s.addShape(p.ShapeType.ellipse,{x:x+.26,y:2.36,w:.43,h:.43,fill:{color:col},line:{color:col,transparency:100}});text(s,label,x+.9,2.41,2.63,.3,22,true,col);text(s,h,x+.27,3.05,3.29,.48,22,true);text(s,b,x+.27,3.81,3.27,1.23,21);});
 text(s,'Critical risk or an unknown critical response can force High risk. The app has no generative AI and does not rate employee performance.',.78,6.02,11.8,.52,19,false,C.muted);
 note(s,'src/scoring.js v2 uses polarity-aware weighted ratios, with critical-answer override. Old records and shared snapshots retain historical calculations unless explicitly recalculated. Displayed guidance is inherited project content, not independently certified legal advice. The slide describes app behavior rather than providing legal advice.');
 s=title(p,'Privacy and governance in the workflow','Share deliberately and keep access limited to the people who need it',5);
 card(p,s,.62,2.02,6.04,4.46,'Governance Center is built','HR sees control status, authorized reviewer count, retention settings and record counts.\n\nRecent audit activity shows governed actions and who performed them.\n\nHR access controls protect review and policy changes.',C.lavender,21);
 card(p,s,6.91,2.02,5.81,4.46,'Privacy and record controls','Private drafts have owner access checks.\n\nRetention is configurable; Slack files follow workspace controls.\n\nDeleting a personal check preserves the submitted HR case and delivered reports.',C.gray,21);
 note(s,'Access controls enforced by handlers and typed storage lookups. Supabase SQL enables RLS and revokes anon/authenticated table privileges; protected Worker service credentials access the tables. This does not remove administrator access. Cron executes configured retention daily; 0 disables it; audit rows remain. Cloud backup and restore was not independently verified.');
 s=title(p,'The app now runs in the cloud','Slack is the interface; the app no longer depends on a Mac process',6);
 [['Slack','Forms, buttons, private notifications',C.lavender],['Cloudflare','Online app, routing and protected settings',C.mint],['Supabase','Checks, shared snapshots, policies and audit records',C.gray]].forEach(([h,b,fill],i)=>card(p,s,.62+i*4.15,2.05,3.83,2.6,h,b,fill,20));
 box(p,s,.62,5.07,12.1,1.62,C.amber);text(s,'What “backed up” means',.88,5.31,11.58,.35,23,true);text(s,'App code and text documentation are saved in GitHub. That is separate from employee-data backup: cloud backup and restore still need verification.',.88,5.86,11.55,.43,20);
 note(s,'Worker deployed October 9 version 492b555c-88fd-4a1b-81b7-991233030340. health/storage returned ok HTTP 200. GitHub source backup dc2865d08a6efdbf6832c53d8bedc4512040bb7e on webhooks. Public source repo excludes credentials, employee databases, operational backups/logs, and binary artifacts pending approval. SQLite and Mac daily backup scripts are legacy/local options; do not describe them as verified Supabase backups.');
 s=title(p,'What was actually checked','Live connection recovery plus automated workflow tests',7);
 card(p,s,.62,2.05,6.04,4.44,'Observed live in Slack','History and a saved assessment opened.\n\nPolicy library and HR queue opened.\n\nThe new-check entry screen opened.\n\nCloud storage health returned OK.',C.mint,21);
 box(p,s,6.91,2.05,5.81,4.44,C.gray);text(s,'Automated evidence',7.17,2.32,5.29,.4,24,true);text(s,'31',7.17,3.06,2.3,.75,50,true,C.purple);text(s,'passing tests',9.22,3.26,2.96,.35,20);text(s,'81',7.17,4.1,2.3,.75,50,true,C.teal);text(s,'Slack payload checks',9.22,4.3,2.96,.6,20);text(s,'External Slack responses are simulated in the tests. Cloud build also passed.',7.17,5.37,5.25,.7,18,false,C.muted);
 note(s,'Test suite executed on October 9 with 31 passing tests; local validator accepted 81 synthetic Block Kit payloads. Not Slack public remote validation during this repair. Tests use real Bolt routing and SQLite with substituted external WebClient responses; they do not demonstrate distributed Supabase race safety. Live checks were read-only and did not alter stored checks/reviews. No new claim of notification/export delivery is made by this repair evidence.');
 s=title(p,'Before a wider rollout','Keep the working pilot and finish the operational checks',8);
 box(p,s,.62,2.05,6.04,4.44,C.lavender);text(s,'Verify reliability',.9,2.32,5.49,.44,24,true);bullets(s,['Test separate manager and HR accounts','Check simultaneous edits in cloud storage','Exercise failed deliveries and retry','Verify a cloud backup and restore'],.98,3.12,5.28,2.84,22);
 box(p,s,6.91,2.05,5.81,4.44,C.mint);text(s,'Confirm rollout settings',7.19,2.32,5.26,.44,24,true);bullets(s,['Confirm HR content and access owners','Confirm agreed retention settings','Assign monitoring, recovery and support','Check mobile and accessible layouts'],7.27,3.12,5.01,2.84,22);
 note(s,'These are outstanding acceptance and operations checks, not claims that the current pilot is broken. Existing automated cases do not establish live two-user behavior or distributed database concurrency. Daily scheduled retention is not a data backup. Do not claim enterprise readiness, SLA, verified cloud restore, AI assistance, scheduled reminder messages, or a quantified risk-reduction result without new evidence.');
 await p.writeFile({fileName:path.join(root,'People Action Check — Updated Pilot Overview.pptx')});
}
main().catch(e=>{console.error(e);process.exit(1)});
